basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: REST API for CodeCover
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CodeCover API
  version: "1.0"
paths: {}
swagger: "2.0"
