basePath: /api/v1
definitions:
  core.Repo:
    properties:
      id:
        type: integer
      name:
        type: string
      nameSpace:
        type: string
      reportID:
        type: string
      scm:
        type: SCMProvider
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for CodeCover
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CodeCover API
  version: "1.0"
paths:
  /repo:
    post:
      parameters:
      - description: repository to create
        in: body
        name: repo
        required: true
        schema:
          $ref: '#/definitions/core.Repo'
      responses:
        "200":
          description: Created repository
          schema:
            $ref: '#/definitions/core.Repo'
      summary: Create new repository for code coverage
      tags:
      - Repository
  /repo/{scm}/{namespace}/{name}:
    get:
      parameters:
      - description: SCM
        in: path
        name: scm
        required: true
        type: string
      - description: Namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: name
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Repo'
      summary: find repository
      tags:
      - Repository
  /repo/{scm}/{namespace}/{name}/report:
    patch:
      parameters:
      - description: SCM
        in: path
        name: scm
        required: true
        type: string
      - description: Namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: name
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: updated repository
          schema:
            $ref: '#/definitions/core.Repo'
      summary: renew repository report id
      tags:
      - Repository
  /report/{id}/{type}:
    post:
      parameters:
      - description: report type
        in: path
        name: type
        required: true
        type: string
      - description: report id
        in: path
        name: id
        required: true
        type: string
      - description: report
        in: formData
        name: file
        required: true
        type: file
      - description: Git commit SHA
        in: formData
        name: commit
        required: true
        type: string
      - description: branch ref
        in: formData
        name: branch
        type: string
      - description: tag ref
        in: formData
        name: tag
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error message
          schema:
            type: string
      summary: Upload coverage report
      tags:
      - Report
  /scm/{scm}/repos:
    get:
      parameters:
      - description: SCM source (github, gitea)
        in: path
        name: scm
        required: true
        type: string
      responses:
        "200":
          description: repositories
          schema:
            items:
              $ref: '#/definitions/core.Repo'
            type: array
      summary: Get repositories from SCM
      tags:
      - SCM
swagger: "2.0"
